### ISSUE TITLE
Please add the required dependencies

### ISSUE THREAD

**Issue by rahuljaguste** [vinayds21/Project-Management-Frontend-ReactJs#1]
➜ npm start

> happay-react@1.0.0 start /Users/rjaguste/Documents/Instawork/Assignments/vinayds
> webpack-dev-server --color --inline --content-base public/ --history-api-fallback

sh: webpack-dev-server: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! happay-react@1.0.0 start: `webpack-dev-server --color --inline --content-base public/ --history-api-fallback`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the happay-react@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by vinayds21** [comment]
Updated with webpack dev server.
